import { useEffect, useMemo, useState } from 'react';
import { KeyRound, UserPlus, ShieldCheck, BadgeCheck, UserCog } from 'lucide-react';
import { api, getStoredUser } from '../lib/api';
import { Actions, Badge, Confirm, Empty, ErrorNotice, Field, Loading, Modal, PageHeader, SearchBox } from '../components/UI';

const roleMap={admin:['Administrador','neutral'],seller:['Vendedor','caramel'],producer:['Produtor','positive']};
const blank={name:'',email:'',password:'',role:'seller',person_id:'',active:true};

export default function Accesses(){
  const [items,setItems]=useState([]),[people,setPeople]=useState([]),[search,setSearch]=useState(''),[editing,setEditing]=useState(null),[remove,setRemove]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const current=getStoredUser();
  const load=()=>Promise.all([api('/users'),api('/people')]).then(([u,p])=>{setItems(u);setPeople(p.filter(x=>x.active))}).finally(()=>setLoading(false));useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>items.filter(i=>`${i.name} ${i.email} ${i.role}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
  const form=editing?.data||blank,availablePeople=people.filter(p=>p.type===form.role),change=(key,value)=>setEditing(e=>({...e,data:{...e.data,[key]:value}}));
  function roleChange(role){const first=people.find(p=>p.type===role);setEditing(e=>({...e,data:{...e.data,role,person_id:role==='admin'?'':String(first?.id||'')}}))}
  async function save(e){e.preventDefault();setError('');try{await api(editing.id?`/users/${editing.id}`:'/users',{method:editing.id?'PUT':'POST',body:form});setEditing(null);await load()}catch(err){setError(err.message)}}
  async function deactivate(){try{await api(`/users/${remove.id}`,{method:'DELETE'});setRemove(null);await load()}catch(err){setRemove(null);setError(err.message)}}
  return <div className="page"><PageHeader eyebrow="Segurança e permissões" title="Acessos" description="Crie o login de cada funcionário e escolha exatamente qual área ele pode acessar." action={<button className="btn primary" onClick={()=>setEditing({data:{...blank,person_id:String(people.find(p=>p.type==='seller')?.id||'')}})}><UserPlus size={18}/> Novo acesso</button>}/><ErrorNotice message={error}/>
    <section className="summary-strip"><div><KeyRound size={20}/><span>Acessos ativos<strong>{items.filter(i=>i.active).length}</strong></span></div><div><ShieldCheck size={20}/><span>Administradores<strong>{items.filter(i=>i.role==='admin'&&i.active).length}</strong></span></div><div><UserCog size={20}/><span>Equipe com login<strong>{items.filter(i=>i.role!=='admin'&&i.active).length}</strong></span></div></section>
    <section className="panel table-panel"><div className="table-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Buscar nome, e-mail ou cargo..."/><span>{filtered.length} acessos</span></div>{loading?<Loading/>:filtered.length?<div className="table-scroll"><table><thead><tr><th>Usuário</th><th>Cargo</th><th>Funcionário vinculado</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(item=><tr key={item.id} className={!item.active?'row-muted':''}><td><div className="cell-title"><div className={`item-symbol ${item.role}`}>{item.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><span><strong>{item.name}</strong><small>{item.email}{item.id===current?.id?' · você':''}</small></span></div></td><td><Badge tone={roleMap[item.role][1]}>{roleMap[item.role][0]}</Badge></td><td>{item.person_name||'Acesso administrativo'}</td><td><Badge tone={item.active?'positive':'muted'}>{item.active?'Ativo':'Inativo'}</Badge></td><td><Actions onEdit={()=>setEditing({id:item.id,data:{...item,person_id:item.person_id?String(item.person_id):'',password:'',active:!!item.active}})} onDelete={item.active&&item.id!==current?.id?()=>setRemove(item):null}/></td></tr>)}</tbody></table></div>:<Empty title="Nenhum acesso encontrado"/>}</section>
    <Modal open={!!editing} title={editing?.id?'Editar acesso':'Criar acesso'} subtitle="O cargo determina menus, registros visíveis e permissões da API." onClose={()=>setEditing(null)}><form onSubmit={save}><ErrorNotice message={error}/><div className="form-grid"><Field label="Nome de exibição" span><input value={form.name} onChange={e=>change('name',e.target.value)} required/></Field><Field label="E-mail de acesso"><input type="email" value={form.email} onChange={e=>change('email',e.target.value)} required/></Field><Field label={editing?.id?'Nova senha (opcional)':'Senha inicial'} hint={editing?.id?'Deixe vazio para manter a senha atual.':'Mínimo de 6 caracteres.'}><input type="password" minLength={editing?.id?0:6} value={form.password} onChange={e=>change('password',e.target.value)} required={!editing?.id}/></Field><Field label="Cargo"><select value={form.role} onChange={e=>roleChange(e.target.value)}><option value="admin">Administrador</option><option value="seller">Vendedor</option><option value="producer">Produtor</option></select></Field>{form.role!=='admin'&&<Field label="Funcionário vinculado"><select value={form.person_id} onChange={e=>change('person_id',e.target.value)} required><option value="">Selecione...</option>{availablePeople.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>}{editing?.id&&<Field label="Situação"><select value={form.active?'1':'0'} onChange={e=>change('active',e.target.value==='1')} disabled={editing.id===current?.id}><option value="1">Ativo</option><option value="0">Inativo</option></select></Field>}</div><div className="permission-preview"><BadgeCheck size={18}/><div><strong>{roleMap[form.role][0]}</strong><span>{form.role==='admin'?'Acesso completo a operação, cadastros e análises.':form.role==='seller'?'Acesso somente ao dashboard pessoal, próprias vendas e transparência.':'Acesso somente ao dashboard pessoal, própria produção e transparência.'}</span></div></div><div className="modal-actions"><button type="button" className="btn ghost" onClick={()=>setEditing(null)}>Cancelar</button><button className="btn primary">Salvar acesso</button></div></form></Modal>
    <Confirm open={!!remove} title="Desativar acesso?" text={`${remove?.name} não conseguirá mais entrar no sistema. O histórico permanecerá intacto.`} onCancel={()=>setRemove(null)} onConfirm={deactivate}/>
  </div>
}
