import { useEffect, useMemo, useState } from 'react';
import { Building2, Plus, Store, HandCoins, PackageCheck, Trash2 } from 'lucide-react';
import { api } from '../lib/api';
import { currency, number } from '../lib/format';
import { Actions, Badge, Confirm, Empty, ErrorNotice, Field, Loading, Modal, PageHeader, SearchBox } from '../components/UI';

const blank={name:'',contact_name:'',phone:'',address:'',active:true,products:[]};

export default function Establishments(){
  const [items,setItems]=useState([]),[products,setProducts]=useState([]),[search,setSearch]=useState(''),[editing,setEditing]=useState(null),[remove,setRemove]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=()=>Promise.all([api('/establishments'),api('/products')]).then(([e,p])=>{setItems(e);setProducts(p.filter(x=>x.active))}).finally(()=>setLoading(false));useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>items.filter(i=>`${i.name} ${i.contact_name}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
  const form=editing?.data||blank,change=(key,value)=>setEditing(e=>({...e,data:{...e.data,[key]:value}}));
  async function edit(item){setError('');const detail=await api(`/establishments/${item.id}`);setEditing({id:item.id,data:{...detail,active:!!detail.active}})}
  function addProduct(){const used=new Set(form.products.map(x=>Number(x.product_id))),first=products.find(p=>!used.has(p.id));if(first)change('products',[...form.products,{product_id:first.id,commission:12}])}
  function updateProduct(index,key,value){change('products',form.products.map((p,i)=>i===index?{...p,[key]:value}:p))}
  async function save(e){e.preventDefault();setError('');try{await api(editing.id?`/establishments/${editing.id}`:'/establishments',{method:editing.id?'PUT':'POST',body:form});setEditing(null);await load()}catch(err){setError(err.message)}}
  async function deactivate(){await api(`/establishments/${remove.id}`,{method:'DELETE'});setRemove(null);load()}
  return <div className="page"><PageHeader eyebrow="Canais parceiros" title="Estabelecimentos" description="Controle onde seus produtos são revendidos, as comissões e o retorno de cada parceiro." action={<button className="btn primary" onClick={()=>setEditing({data:{...blank,products:[]}})}><Plus size={18}/> Novo parceiro</button>}/><ErrorNotice message={error}/>
    <section className="summary-strip"><div><Store size={20}/><span>Parceiros ativos<strong>{items.filter(i=>i.active).length}</strong></span></div><div><PackageCheck size={20}/><span>Unidades revendidas<strong>{number(items.reduce((s,i)=>s+i.units_sold,0))}</strong></span></div><div><HandCoins size={20}/><span>Comissões geradas<strong>{currency(items.reduce((s,i)=>s+i.earnings,0))}</strong></span></div></section>
    <section className="partner-grid">{loading?<Loading/>:filtered.length?filtered.map(item=><article className={`panel partner-card ${!item.active?'row-muted':''}`} key={item.id}><div className="partner-head"><div className="item-symbol partner"><Building2 size={18}/></div><div><h2>{item.name}</h2><span>{item.contact_name||'Sem contato informado'}</span></div><Actions onEdit={()=>edit(item)} onDelete={item.active?()=>setRemove(item):null}/></div><div className="partner-metrics"><div><span>Faturamento</span><strong>{currency(item.revenue)}</strong></div><div><span>Comissão</span><strong>{currency(item.earnings)}</strong></div><div><span>Produtos</span><strong>{item.product_count}</strong></div></div><div className="partner-foot"><span>{item.phone||'Sem telefone'}</span><Badge tone={item.active?'positive':'muted'}>{item.active?'Ativo':'Inativo'}</Badge></div></article>):<Empty title="Nenhum parceiro encontrado"/>}</section>
    <Modal open={!!editing} title={editing?.id?'Editar parceiro':'Novo estabelecimento parceiro'} subtitle="Escolha os produtos revendidos e a comissão de cada um." onClose={()=>setEditing(null)} wide><form onSubmit={save}><ErrorNotice message={error}/><div className="form-grid"><Field label="Nome do estabelecimento"><input value={form.name} onChange={e=>change('name',e.target.value)} required/></Field><Field label="Pessoa de contato"><input value={form.contact_name} onChange={e=>change('contact_name',e.target.value)}/></Field><Field label="Telefone"><input value={form.phone} onChange={e=>change('phone',e.target.value)}/></Field><Field label="Endereço"><input value={form.address} onChange={e=>change('address',e.target.value)}/></Field></div><div className="form-section-title"><div><span>Produtos revendidos</span><small>A comissão fica registrada em cada venda.</small></div><button type="button" className="btn small ghost" onClick={addProduct} disabled={form.products.length>=products.length}><Plus size={15}/> Produto</button></div><div className="partner-products">{form.products.length?form.products.map((item,index)=><div className="partner-product-row" key={`${item.product_id}-${index}`}><Field label="Produto"><select value={item.product_id} onChange={e=>updateProduct(index,'product_id',Number(e.target.value))}>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Comissão do parceiro (%)"><input type="number" min="0" max="100" step="0.1" value={item.commission} onChange={e=>updateProduct(index,'commission',e.target.value)}/></Field><button type="button" className="icon-btn danger" onClick={()=>change('products',form.products.filter((_,i)=>i!==index))}><Trash2 size={16}/></button></div>):<div className="recipe-empty">Adicione os produtos que este estabelecimento pode revender.</div>}</div><div className="modal-actions"><button type="button" className="btn ghost" onClick={()=>setEditing(null)}>Cancelar</button><button className="btn primary">Salvar parceiro</button></div></form></Modal>
    <Confirm open={!!remove} title="Desativar parceiro?" text={`“${remove?.name}” não aparecerá em novas vendas, mas seu histórico será preservado.`} onCancel={()=>setRemove(null)} onConfirm={deactivate}/>
  </div>
}
