import { useEffect, useMemo, useState } from 'react';
import { CakeSlice, Plus, Calculator, Trash2, Boxes, TrendingUp } from 'lucide-react';
import { api } from '../lib/api';
import { currency, number, percent } from '../lib/format';
import { Actions, Badge, Confirm, Empty, ErrorNotice, Field, Loading, Modal, PageHeader, SearchBox } from '../components/UI';

const blank={name:'',category:'Bolo de pote',sale_price:14,packaging_cost:.76,other_cost:0,sales_fee:3.5,seller_commission:15,producer_commission:15,cash_percentage:20,active:true,recipe:[]};

export default function Products(){
  const [items,setItems]=useState([]),[ingredients,setIngredients]=useState([]),[search,setSearch]=useState(''),[editing,setEditing]=useState(null),[remove,setRemove]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
  const load=()=>Promise.all([api('/products'),api('/ingredients')]).then(([p,i])=>{setItems(p);setIngredients(i)}).finally(()=>setLoading(false));useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>items.filter(i=>`${i.name} ${i.category}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
  const form=editing?.data||blank,change=(key,value)=>setEditing(e=>({...e,data:{...e.data,[key]:value}}));
  const recipeCost=(form.recipe||[]).reduce((sum,item)=>{const ing=ingredients.find(i=>i.id===Number(item.ingredient_id));return sum+(ing?.unit_cost||0)*Number(item.quantity||0)},0);
  const totalCost=recipeCost+Number(form.packaging_cost||0)+Number(form.other_cost||0),deductions=Number(form.sale_price||0)*(Number(form.sales_fee||0)+Number(form.seller_commission||0)+Number(form.producer_commission||0)+Number(form.cash_percentage||0))/100;
  const profit=Number(form.sale_price||0)-totalCost-deductions,margin=Number(form.sale_price)?profit/Number(form.sale_price)*100:0;
  async function edit(item){setError('');const detail=await api(`/products/${item.id}`);setEditing({id:item.id,data:{...detail,active:!!detail.active}})}
  async function save(e){e.preventDefault();setSaving(true);setError('');try{await api(editing.id?`/products/${editing.id}`:'/products',{method:editing.id?'PUT':'POST',body:form});setEditing(null);await load()}catch(err){setError(err.message)}finally{setSaving(false)}}
  async function deactivate(){await api(`/products/${remove.id}`,{method:'DELETE'});setRemove(null);load()}
  function addRecipe(){const used=new Set((form.recipe||[]).map(i=>Number(i.ingredient_id))),first=ingredients.find(i=>!used.has(i.id));if(first)change('recipe',[...(form.recipe||[]),{ingredient_id:first.id,quantity:0}])}
  function updateRecipe(index,key,value){change('recipe',form.recipe.map((r,i)=>i===index?{...r,[key]:value}:r))}
  return <div className="page">
    <PageHeader eyebrow="Cardápio & precificação" title="Produtos e custos" description="Monte a ficha técnica e saiba exatamente quanto sobra em cada venda." action={<button className="btn primary" onClick={()=>setEditing({data:{...blank,recipe:[]}})}><Plus size={18}/> Novo produto</button>}/><ErrorNotice message={error}/>
    <section className="summary-strip"><div><CakeSlice size={20}/><span>Produtos ativos<strong>{items.filter(i=>i.active).length}</strong></span></div><div><TrendingUp size={20}/><span>Margem média<strong>{percent(items.length?items.reduce((s,i)=>s+i.margin,0)/items.length:0)}</strong></span></div><div><Boxes size={20}/><span>Estoque pronto estimado<strong>{number(items.reduce((s,i)=>s+Math.max(0,i.available_stock),0))} un.</strong></span></div></section>
    <section className="panel table-panel"><div className="table-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Buscar produto ou categoria..."/><span>{filtered.length} produtos</span></div>{loading?<Loading/>:filtered.length?<div className="table-scroll"><table><thead><tr><th>Produto</th><th>Preço</th><th>Custo unitário</th><th>Lucro unitário</th><th>Margem</th><th>Estoque pronto</th><th></th></tr></thead><tbody>{filtered.map(item=><tr key={item.id} className={!item.active?'row-muted':''}><td><div className="cell-title"><div className="item-symbol product"><CakeSlice size={17}/></div><span><strong>{item.name}</strong><small>{item.category}</small></span></div></td><td><strong>{currency(item.sale_price)}</strong></td><td>{currency(item.unit_cost)}</td><td className={item.unit_profit>=0?'positive-text':'negative-text'}>{currency(item.unit_profit)}</td><td><Badge tone={item.margin>=20?'positive':item.margin>=0?'warning':'danger'}>{percent(item.margin)}</Badge></td><td>{number(Math.max(0,item.available_stock))} un.</td><td><Actions onEdit={()=>edit(item)} onDelete={item.active?()=>setRemove(item):null}/></td></tr>)}</tbody></table></div>:<Empty title="Nenhum produto encontrado"/>}</section>
    <Modal open={!!editing} title={editing?.id?'Editar ficha técnica':'Novo produto'} subtitle="Defina ingredientes por unidade produzida. O cálculo é automático." onClose={()=>setEditing(null)} wide>
      <form onSubmit={save}><ErrorNotice message={error}/><div className="product-form-layout"><div className="product-form-main"><div className="form-grid"><Field label="Nome do produto"><input value={form.name} onChange={e=>change('name',e.target.value)} placeholder="Ex.: Ninho com morango" required/></Field><Field label="Categoria" hint="Pode ser alterada para novos tipos no futuro."><input value={form.category} onChange={e=>change('category',e.target.value)} required/></Field><Field label="Preço de venda (R$)"><input type="number" step="0.01" min="0" value={form.sale_price} onChange={e=>change('sale_price',e.target.value)} required/></Field><Field label="Custo embalagem (R$)"><input type="number" step="0.01" min="0" value={form.packaging_cost} onChange={e=>change('packaging_cost',e.target.value)}/></Field></div>
        <div className="form-section-title"><div><span>Receita por unidade</span><small>Use a mesma unidade de compra do insumo</small></div><button type="button" className="btn small ghost" onClick={addRecipe} disabled={form.recipe.length>=ingredients.length}><Plus size={15}/> Ingrediente</button></div>
        <div className="recipe-list">{form.recipe.length?form.recipe.map((item,index)=>{const ing=ingredients.find(i=>i.id===Number(item.ingredient_id));return <div className="recipe-row" key={`${item.ingredient_id}-${index}`}><Field label="Insumo"><select value={item.ingredient_id} onChange={e=>updateRecipe(index,'ingredient_id',Number(e.target.value))}>{ingredients.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></Field><Field label={`Quantidade (${ing?.unit||'un'})`}><input type="number" step="0.01" min="0" value={item.quantity} onChange={e=>updateRecipe(index,'quantity',e.target.value)}/></Field><div className="recipe-cost"><span>Custo</span><strong>{currency((ing?.unit_cost||0)*Number(item.quantity||0))}</strong></div><button type="button" className="icon-btn danger" onClick={()=>change('recipe',form.recipe.filter((_,i)=>i!==index))}><Trash2 size={16}/></button></div>}):<div className="recipe-empty">Adicione os ingredientes usados em uma unidade deste produto.</div>}</div>
        <div className="form-section-title"><div><span>Custos e deduções</span><small>Valores aplicados em cada unidade vendida</small></div></div><div className="form-grid three"><Field label="Outros custos (R$)"><input type="number" step="0.01" min="0" value={form.other_cost} onChange={e=>change('other_cost',e.target.value)}/></Field><Field label="Taxa de venda (%)"><input type="number" step="0.1" min="0" value={form.sales_fee} onChange={e=>change('sales_fee',e.target.value)}/></Field><Field label="Comissão vendedor (%)"><input type="number" step="0.1" min="0" value={form.seller_commission} onChange={e=>change('seller_commission',e.target.value)}/></Field><Field label="Comissão produtor (%)"><input type="number" step="0.1" min="0" value={form.producer_commission} onChange={e=>change('producer_commission',e.target.value)}/></Field><Field label="Reserva de caixa (%)"><input type="number" step="0.1" min="0" value={form.cash_percentage} onChange={e=>change('cash_percentage',e.target.value)}/></Field>{editing?.id&&<Field label="Situação"><select value={form.active?'1':'0'} onChange={e=>change('active',e.target.value==='1')}><option value="1">Ativo</option><option value="0">Inativo</option></select></Field>}</div></div>
        <aside className="cost-preview"><div className="cost-preview-head"><Calculator size={19}/><span>Resumo por unidade</span></div><div className="cost-line"><span>Ingredientes</span><strong>{currency(recipeCost)}</strong></div><div className="cost-line"><span>Embalagem + outros</span><strong>{currency(Number(form.packaging_cost||0)+Number(form.other_cost||0))}</strong></div><div className="cost-line"><span>Taxas e comissões</span><strong>{currency(deductions)}</strong></div><div className="cost-divider"/><div className="cost-line total"><span>Custo total</span><strong>{currency(totalCost+deductions)}</strong></div><div className={`profit-card ${profit<0?'bad':''}`}><span>Lucro estimado</span><strong>{currency(profit)}</strong><small>{percent(margin)} de margem</small></div><p>O custo dos ingredientes acompanha automaticamente o preço de compra dos insumos.</p></aside></div>
        <div className="modal-actions"><button type="button" className="btn ghost" onClick={()=>setEditing(null)}>Cancelar</button><button className="btn primary" disabled={saving}>{saving?'Salvando...':'Salvar ficha técnica'}</button></div></form>
    </Modal>
    <Confirm open={!!remove} title="Desativar produto?" text={`“${remove?.name}” deixará de aparecer em novos lançamentos. Todo o histórico será mantido.`} onCancel={()=>setRemove(null)} onConfirm={deactivate}/>
  </div>
}
