import { useEffect, useMemo, useState } from 'react';
import { Plus, CookingPot, CalendarClock, CheckCircle2, Boxes } from 'lucide-react';
import { api, getStoredUser } from '../lib/api';
import { currency, dateBR, inputDate, number } from '../lib/format';
import { Actions, Badge, Confirm, Empty, ErrorNotice, Field, Loading, Modal, PageHeader, SearchBox } from '../components/UI';

const statusMap={planned:['Planejada','neutral'],in_progress:['Em produção','warning'],completed:['Concluída','positive']};
const makeBlank=()=>({product_id:'',producer_id:'',quantity:20,status:'planned',produced_at:inputDate(),notes:''});

export default function Production(){
  const user=getStoredUser(),isAdmin=user?.role==='admin';
  const [items,setItems]=useState([]),[products,setProducts]=useState([]),[people,setPeople]=useState([]),[search,setSearch]=useState(''),[editing,setEditing]=useState(null),[remove,setRemove]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=()=>Promise.all([api('/production'),api('/products'),isAdmin?api('/people?type=producer'):Promise.resolve([])]).then(([a,b,c])=>{setItems(a);setProducts(b.filter(x=>x.active));setPeople(c.filter(x=>x.active))}).finally(()=>setLoading(false));useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>items.filter(i=>`${i.product_name} ${i.producer_name||''}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
  const form=editing?.data||makeBlank(),change=(key,value)=>setEditing(e=>({...e,data:{...e.data,[key]:value}}));
  function open(item){const data=item?{...item,product_id:String(item.product_id),producer_id:item.producer_id?String(item.producer_id):'',produced_at:inputDate(item.produced_at)}:{...makeBlank(),product_id:String(products[0]?.id||''),producer_id:String(people[0]?.id||'')};setEditing({id:item?.id,data})}
  async function save(e){e.preventDefault();setError('');try{await api(editing.id?`/production/${editing.id}`:'/production',{method:editing.id?'PUT':'POST',body:{...form,produced_at:new Date(`${form.produced_at}T12:00:00`).toISOString()}});setEditing(null);await load()}catch(err){setError(err.message)}}
  async function del(){await api(`/production/${remove.id}`,{method:'DELETE'});setRemove(null);load()}
  return <div className="page"><PageHeader eyebrow={isAdmin?'Operação':'Minha operação'} title={isAdmin?'Produção':'Minha produção'} description={isAdmin?'Planeje lotes, atribua responsáveis e acompanhe o que já ficou pronto.':'Registre seus lotes e acompanhe somente a produção vinculada ao seu acesso.'} action={<button className="btn primary" onClick={()=>open()}><Plus size={18}/> Novo lote</button>}/><ErrorNotice message={error}/>
    <section className="summary-strip"><div><CookingPot size={20}/><span>Unidades planejadas<strong>{number(items.filter(i=>i.status==='planned').reduce((s,i)=>s+i.quantity,0))}</strong></span></div><div><CalendarClock size={20}/><span>Em produção<strong>{number(items.filter(i=>i.status==='in_progress').reduce((s,i)=>s+i.quantity,0))}</strong></span></div><div><CheckCircle2 size={20}/><span>Concluídas<strong>{number(items.filter(i=>i.status==='completed').reduce((s,i)=>s+i.quantity,0))}</strong></span></div></section>
    <section className="panel table-panel"><div className="table-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Buscar produto ou responsável..."/><span>{filtered.length} lotes</span></div>{loading?<Loading/>:filtered.length?<div className="table-scroll"><table><thead><tr><th>Produto</th><th>Data</th><th>Responsável</th><th>Quantidade</th><th>Custo estimado</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><div className="cell-title"><div className="item-symbol production"><Boxes size={17}/></div><span><strong>{item.product_name}</strong><small>{item.notes||'Sem observações'}</small></span></div></td><td>{dateBR(item.produced_at)}</td><td>{item.producer_name||'—'}</td><td><strong>{item.quantity} un.</strong></td><td>{currency(item.total_cost)}</td><td><Badge tone={statusMap[item.status][1]}>{statusMap[item.status][0]}</Badge></td><td><Actions onEdit={()=>open(item)} onDelete={()=>setRemove(item)}/></td></tr>)}</tbody></table></div>:<Empty title="Nenhum lote encontrado" text="Crie um lote para começar a planejar a cozinha."/>}</section>
    <Modal open={!!editing} title={editing?.id?'Editar lote':'Novo lote de produção'} subtitle="Organize o que será produzido e acompanhe o andamento." onClose={()=>setEditing(null)}><form onSubmit={save}><div className="form-grid"><Field label="Produto" span><select value={form.product_id} onChange={e=>change('product_id',e.target.value)} required><option value="">Selecione...</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Quantidade"><input type="number" min="1" value={form.quantity} onChange={e=>change('quantity',e.target.value)} required/></Field><Field label="Data de produção"><input type="date" value={form.produced_at} onChange={e=>change('produced_at',e.target.value)} required/></Field>{isAdmin&&<Field label="Produtor"><select value={form.producer_id} onChange={e=>change('producer_id',e.target.value)} required><option value="">Selecione...</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>}<Field label="Status"><select value={form.status} onChange={e=>change('status',e.target.value)}>{Object.entries(statusMap).map(([k,v])=><option key={k} value={k}>{v[0]}</option>)}</select></Field><Field label="Observações" span><textarea rows="3" value={form.notes} onChange={e=>change('notes',e.target.value)} placeholder="Ex.: separar frutas pela manhã"/></Field></div><div className="modal-actions"><button type="button" className="btn ghost" onClick={()=>setEditing(null)}>Cancelar</button><button className="btn primary">Salvar lote</button></div></form></Modal>
    <Confirm open={!!remove} title="Excluir lote?" text="O lote será removido do histórico de produção." onCancel={()=>setRemove(null)} onConfirm={del}/>
  </div>
}
