import { useEffect, useMemo, useState } from 'react';
import { Plus, ShoppingBag, CircleDollarSign, ReceiptText, Scale } from 'lucide-react';
import { api } from '../lib/api';
import { getStoredUser } from '../lib/api';
import { currency, dateBR, inputDate, number } from '../lib/format';
import { Actions, Badge, Confirm, Empty, ErrorNotice, Field, Loading, Modal, PageHeader, SearchBox } from '../components/UI';

const statusMap={paid:['Pago','positive'],pending:['Pendente','warning'],cancelled:['Cancelado','danger']};
const makeBlank=()=>({product_id:'',seller_id:'',producer_id:'',establishment_id:'',quantity:1,unit_price:'',channel:'WhatsApp',status:'paid',sold_at:inputDate()});

export default function Sales(){
  const user=getStoredUser(),isAdmin=user?.role==='admin';
  const [items,setItems]=useState([]),[products,setProducts]=useState([]),[people,setPeople]=useState([]),[producers,setProducers]=useState([]),[partners,setPartners]=useState([]),[search,setSearch]=useState(''),[editing,setEditing]=useState(null),[remove,setRemove]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=()=>Promise.all([api('/sales'),api('/products'),api('/establishments'),isAdmin?api('/people'):Promise.resolve([])]).then(([a,b,e,c])=>{setItems(a);setProducts(b.filter(x=>x.active));setPartners(e.filter(x=>x.active));setPeople(c.filter(x=>x.active&&x.type==='seller'));setProducers(c.filter(x=>x.active&&x.type==='producer'))}).finally(()=>setLoading(false));useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>items.filter(i=>`${i.product_name} ${i.seller_name||''} ${i.channel}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
  const form=editing?.data||makeBlank(),change=(key,value)=>setEditing(e=>({...e,data:{...e.data,[key]:value}}));
  function open(item){const first=products[0];const data=item?{...item,product_id:String(item.product_id),seller_id:item.seller_id?String(item.seller_id):'',producer_id:item.producer_id?String(item.producer_id):'',establishment_id:item.establishment_id?String(item.establishment_id):'',sold_at:inputDate(item.sold_at)}:{...makeBlank(),product_id:String(first?.id||''),seller_id:String(people[0]?.id||''),producer_id:String(producers[0]?.id||''),unit_price:first?.sale_price||''};setEditing({id:item?.id,data})}
  function productChanged(value){const p=products.find(x=>x.id===Number(value));setEditing(e=>({...e,data:{...e.data,product_id:value,unit_price:p?.sale_price||'',establishment_id:''}}))}
  async function save(e){e.preventDefault();setError('');try{await api(editing.id?`/sales/${editing.id}`:'/sales',{method:editing.id?'PUT':'POST',body:{...form,sold_at:new Date(`${form.sold_at}T12:00:00`).toISOString()}});setEditing(null);await load()}catch(err){setError(err.message)}}
  async function del(){await api(`/sales/${remove.id}`,{method:'DELETE'});setRemove(null);load()}
  const valid=items.filter(i=>i.status!=='cancelled'),revenue=valid.reduce((s,i)=>s+i.total,0),cost=valid.reduce((s,i)=>s+i.estimated_cost,0),units=valid.reduce((s,i)=>s+i.quantity,0);
  const personalEarnings=valid.reduce((s,i)=>s+(i.seller_earning||0),0),eligiblePartners=partners.filter(p=>!form.product_id||String(p.product_ids||'').split(',').includes(String(form.product_id)));
  return <div className="page"><PageHeader eyebrow={isAdmin?'Comercial':'Meu comercial'} title={isAdmin?'Vendas':'Minhas vendas'} description={isAdmin?'Registre as saídas e acompanhe faturamento, canais e responsáveis.':'Registre somente suas vendas e acompanhe sua comissão em tempo real.'} action={<button className="btn primary" onClick={()=>open()}><Plus size={18}/> Nova venda</button>}/><ErrorNotice message={error}/>
    <section className="summary-strip"><div><CircleDollarSign size={20}/><span>{isAdmin?'Faturamento registrado':'Faturamento que gerei'}<strong>{currency(revenue)}</strong></span></div><div><ShoppingBag size={20}/><span>Unidades vendidas<strong>{number(units)}</strong></span></div><div><Scale size={20}/><span>{isAdmin?'Resultado bruto estimado':'Minha comissão'}<strong>{currency(isAdmin?revenue-cost:personalEarnings)}</strong></span></div></section>
    <section className="panel table-panel"><div className="table-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Buscar produto, vendedor ou canal..."/><span>{filtered.length} lançamentos</span></div>{loading?<Loading/>:filtered.length?<div className="table-scroll"><table><thead><tr><th>Produto</th><th>Data</th><th>Vendedor</th><th>Canal</th><th>Parceiro</th><th>Quantidade</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(item=><tr key={item.id} className={item.status==='cancelled'?'row-muted':''}><td><div className="cell-title"><div className="item-symbol sale"><ReceiptText size={17}/></div><span><strong>{item.product_name}</strong><small>{currency(item.unit_price)} por unidade</small></span></div></td><td>{dateBR(item.sold_at)}</td><td>{item.seller_name||'—'}</td><td>{item.channel}</td><td>{item.establishment_name||'—'}</td><td>{item.quantity} un.</td><td><strong>{currency(item.total)}</strong></td><td><Badge tone={statusMap[item.status][1]}>{statusMap[item.status][0]}</Badge></td><td><Actions onEdit={()=>open(item)} onDelete={()=>setRemove(item)}/></td></tr>)}</tbody></table></div>:<Empty title="Nenhuma venda encontrada" text="Registre uma venda para alimentar seus indicadores."/>}</section>
    <Modal open={!!editing} title={editing?.id?'Editar venda':'Registrar nova venda'} subtitle="O lançamento atualiza automaticamente os indicadores e as comissões." onClose={()=>setEditing(null)}><form onSubmit={save}><div className="form-grid"><Field label="Produto" span><select value={form.product_id} onChange={e=>productChanged(e.target.value)} required><option value="">Selecione...</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Quantidade"><input type="number" min="1" value={form.quantity} onChange={e=>change('quantity',e.target.value)} required/></Field><Field label="Preço unitário (R$)"><input type="number" min="0" step="0.01" value={form.unit_price} onChange={e=>change('unit_price',e.target.value)} required/></Field><Field label="Data da venda"><input type="date" value={form.sold_at} onChange={e=>change('sold_at',e.target.value)} required/></Field>{isAdmin&&<Field label="Vendedor"><select value={form.seller_id} onChange={e=>change('seller_id',e.target.value)} required><option value="">Selecione...</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>}{isAdmin&&<Field label="Produtor responsável"><select value={form.producer_id} onChange={e=>change('producer_id',e.target.value)}><option value="">Automático pelo último lote</option>{producers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>}<Field label="Estabelecimento parceiro"><select value={form.establishment_id} onChange={e=>change('establishment_id',e.target.value)}><option value="">Venda sem parceiro</option>{eligiblePartners.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Canal"><select value={form.channel} onChange={e=>change('channel',e.target.value)}><option>WhatsApp</option><option>Instagram</option><option>Encomenda</option><option>Loja</option><option>iFood</option><option>Direto</option></select></Field><Field label="Status"><select value={form.status} onChange={e=>change('status',e.target.value)}>{Object.entries(statusMap).map(([k,v])=><option key={k} value={k}>{v[0]}</option>)}</select></Field></div><div className="sale-preview"><span>Total desta venda</span><strong>{currency(Number(form.quantity||0)*Number(form.unit_price||0))}</strong></div><div className="modal-actions"><button type="button" className="btn ghost" onClick={()=>setEditing(null)}>Cancelar</button><button className="btn primary">Salvar venda</button></div></form></Modal>
    <Confirm open={!!remove} title="Excluir venda?" text="O lançamento será removido e os indicadores serão recalculados." onCancel={()=>setRemove(null)} onConfirm={del}/>
  </div>
}
